### ISSUE TITLE
Submit path to be only shown if the user is logged in

### ISSUE THREAD

**Issue by nabendu82** [nabendu82/hackernews-react#1]
Submit path to be only shown if the user is logged in. If he/she is not logged in, redirect to login page, which have a login button

**Comment by zouxuoz** [comment]
@nabendu82 u could implement `PrivateRoute`/`ProtectedRoute` based on the `isAuthorized` flag

**Comment by nabendu82** [comment]
Fixed by #4ad655b7ff
