### ISSUE TITLE
If the user is logged in the logout should be shown, otherwise login

### ISSUE THREAD

**Issue by nabendu82** [nabendu82/hackernews-react#2]
If the user is logged in then the logout link should be shown, otherwise the logout link should be show. Currently hardcoded to login/logout
![image](https://user-images.githubusercontent.com/17110163/61587078-a9005880-aba0-11e9-9b0b-92c27ac48c90.png)

**Comment by zouxuoz** [comment]
@nabendu82 u could use conditional rendering based on the `isAuthorized` flag which u could get via `withAuth` hoc or `useContext(AuthContext)` hook access

**Comment by nabendu82** [comment]
Fixed by #4ad655b7ff
